### ISSUE TITLE
Import log from .csv - extended features

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#554]
### User story: Import log from .csv - extended features ###
Continuance from features implemented in user story #174 in order to increase the robustness of the import log feature.

### Acceptance criteria ###
- [x] #502 When importing log data, values with same index will be overwritten. Informing the user could be useful.
- [x] #501 When importing large files, give user progress feedback through the already established websocket 
- [x] #500 Constraint checking CSV import log to be able to import large files
- [x] #499 Create missing curves/mnemonic when importing CSV file will make creating and importing test data to an empty log possible.
- [x] #498 Trim input before processing, to make import more robust when importing synthetic data 

### Resources ###

-  Lead resource: [name/company]
-  Contributors: [list names/company]

**Comment by eliasbruvik** [comment]
All implemented
